#!/bin/sh

if [ "${1:-}" = "-V" ]; then
  printf 'tmux 999.0\n'
  exit 0
fi

if [ -z "${DOTFILES_FAKE_TMUX_LOG:-}" ]; then
  printf 'fake tmux: DOTFILES_FAKE_TMUX_LOG is required\n' >&2
  exit 1
fi

case "${1:-}" in
  list-clients)
    printf '%b' "${DOTFILES_FAKE_TMUX_CLIENT_CONTROL_MODES:-}"
    ;;
  set-option | set-window-option)
    printf '%s\n' "$*" >>"$DOTFILES_FAKE_TMUX_LOG"
    ;;
  *)
    printf '%s\n' "$*" >>"$DOTFILES_FAKE_TMUX_LOG"
    ;;
esac
